name = "dishbloom"
compatibility_date = "2024-12-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "dishbloom-db"
database_id = "f0be6ee0-20f2-4e3e-a71f-d93c788179f8"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "dishbloom-images"
